use_frameworks!

target 'GPNavigationController_Example' do
  pod 'GPNavigationController', :path => '../'

  target 'GPNavigationController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
